---
name: acme.sh
version: 2.1.3
slug: acmesh
description: "ACME.sh local CA"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 80
ingress_stream: true
ports:
  80/tcp: 80
