---
name: acme.sh
version: 2.1.3
slug: acmesh
description: "ACME.sh local CA"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
uart: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
startup: once
init: false
ingress: true
ingress_port: 8080
ingress_stream: true
ports:
  80/tcp: 8080
map:
  - type: ssl
    read_only: false
